時間割を管理する画面の作成
team-gleam/kiwi pull request #13
Opened 2020-04-14 07:45 UTC by narupi

・時間割の表示
・時間割セルを長押しすることでダイアログを表示して時間割を登録する

2020-04-15 13:27 UTC, Index197511 requested changes

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/net/KiwiClient.kt
> +    private var token = "token"
テスト環境が残ってしまっているので削除をお願いします

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/net/KiwiService.kt
> +    private val API_URL = "http://10.0.2.2:3000"
テスト環境が残っているので修正お願いします

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +    }
内部でsuperを呼ぶだけならここに関数を書く必要はないので削除してもいいと思います

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +    }
同上です

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +            }
alsoの中身が実装されていませんが、何か意図があるものですか？

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +        timetableFragmentBinding.handlers = this
applyを使用してもいいと思います

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableRegisterDialogFragment.kt
> +    private val _dayOfWeek: TimetableEnum = dayOfWeek
内部で_dayOfWeekに代入するよりもこちらの方がいいと思います
```kotlin
class TimetableRegisterDialogFragment(private val dayOfWeek: TimetableEnum)
```

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/view/TimetableRegisterDialogFragment.kt
> +            val registerView = activity!!.layoutInflater.inflate(R.layout.timetable_register_dialog_fragment, null)
" !! " はあまりよろしいものではない気がします

2020-04-15 13:27 UTC, Index197511 commented on app/src/main/java/com/gleam/kiwi/viewmodel/TimetableViewModel.kt
> +    val timetable: LiveData<Timetable>?
`(Mutable)LiceData<Timetable>?`ではなく`(Mutable)LiveData<Timetable?>`ではありませんか？

2020-04-17 01:27 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/net/KiwiClient.kt
> +    private var token = "token"
修正しました

2020-04-17 01:27 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/net/KiwiService.kt
> +    private val API_URL = "http://10.0.2.2:3000"
修正しました

2020-04-17 01:27 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +    }
削除しました

2020-04-17 01:27 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +    }
削除しました

2020-04-17 01:28 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +            }
削除しました

2020-04-17 01:32 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt
> +        timetableFragmentBinding.handlers = this
修正しました
https://github.com/team-gleam/kiwi/blob/560420f6b863519018b92e38444e65bf1efec5e1/app/src/main/java/com/gleam/kiwi/view/TimetableFragment.kt#L28-L32

2020-04-17 01:32 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableRegisterDialogFragment.kt
> +    private val _dayOfWeek: TimetableEnum = dayOfWeek
修正しました

2020-04-17 01:32 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/view/TimetableRegisterDialogFragment.kt
> +            val registerView = activity!!.layoutInflater.inflate(R.layout.timetable_register_dialog_fragment, null)
修正しました

2020-04-17 01:33 UTC, narupi commented on app/src/main/java/com/gleam/kiwi/viewmodel/TimetableViewModel.kt
> +    val timetable: LiveData<Timetable>?
修正しました

2020-04-17 03:30 UTC, Index197511 reviewed
LGTM
あとはblackbrackenに任せます

2020-04-17 07:06 UTC, blackbracken commented on app/src/main/java/com/gleam/kiwi/net/KiwiClient.kt
> +    private var token = "token"
:100:

2020-04-17 07:07 UTC, blackbracken approved these changes

2020-04-17 08:54 UTC, merged